export const PLANS = {
  // MTN Plans
  mtn_500mb_7d: {
    id: 'mtn_500mb_7d',
    network: 'MTN',
    name: '500MB — 7 Days',
    data_size: '500MB',
    validity: '7 days',
    retail_price: 200,
    wholesale_price: 150,
    vtu_plan_code: 'MTN_SME_500MB_7',
    featured: false,
  },
  mtn_1gb_30d: {
    id: 'mtn_1gb_30d',
    network: 'MTN',
    name: '1GB — 30 Days',
    data_size: '1GB',
    validity: '30 days',
    retail_price: 350,
    wholesale_price: 270,
    vtu_plan_code: 'MTN_SME_1GB_30',
    featured: true,
  },
  mtn_2gb_30d: {
    id: 'mtn_2gb_30d',
    network: 'MTN',
    name: '2GB — 30 Days',
    data_size: '2GB',
    validity: '30 days',
    retail_price: 650,
    wholesale_price: 500,
    vtu_plan_code: 'MTN_SME_2GB_30',
    featured: false,
  },
  mtn_5gb_30d: {
    id: 'mtn_5gb_30d',
    network: 'MTN',
    name: '5GB — 30 Days',
    data_size: '5GB',
    validity: '30 days',
    retail_price: 1500,
    wholesale_price: 1200,
    vtu_plan_code: 'MTN_SME_5GB_30',
    featured: false,
  },
  mtn_10gb_30d: {
    id: 'mtn_10gb_30d',
    network: 'MTN',
    name: '10GB — 30 Days',
    data_size: '10GB',
    validity: '30 days',
    retail_price: 2800,
    wholesale_price: 2200,
    vtu_plan_code: 'MTN_SME_10GB_30',
    featured: false,
  },

  // Airtel Plans
  airtel_500mb_7d: {
    id: 'airtel_500mb_7d',
    network: 'Airtel',
    name: '500MB — 7 Days',
    data_size: '500MB',
    validity: '7 days',
    retail_price: 200,
    wholesale_price: 150,
    vtu_plan_code: 'AIRTEL_SME_500MB_7',
    featured: false,
  },
  airtel_1gb_30d: {
    id: 'airtel_1gb_30d',
    network: 'Airtel',
    name: '1GB — 30 Days',
    data_size: '1GB',
    validity: '30 days',
    retail_price: 350,
    wholesale_price: 270,
    vtu_plan_code: 'AIRTEL_SME_1GB_30',
    featured: true,
  },
  airtel_2gb_30d: {
    id: 'airtel_2gb_30d',
    network: 'Airtel',
    name: '2GB — 30 Days',
    data_size: '2GB',
    validity: '30 days',
    retail_price: 650,
    wholesale_price: 500,
    vtu_plan_code: 'AIRTEL_SME_2GB_30',
    featured: false,
  },
  airtel_5gb_30d: {
    id: 'airtel_5gb_30d',
    network: 'Airtel',
    name: '5GB — 30 Days',
    data_size: '5GB',
    validity: '30 days',
    retail_price: 1500,
    wholesale_price: 1200,
    vtu_plan_code: 'AIRTEL_SME_5GB_30',
    featured: false,
  },

  // Glo Plans
  glo_1gb_30d: {
    id: 'glo_1gb_30d',
    network: 'Glo',
    name: '1GB — 30 Days',
    data_size: '1GB',
    validity: '30 days',
    retail_price: 300,
    wholesale_price: 230,
    vtu_plan_code: 'GLO_SME_1GB_30',
    featured: true,
  },
  glo_2gb_30d: {
    id: 'glo_2gb_30d',
    network: 'Glo',
    name: '2GB — 30 Days',
    data_size: '2GB',
    validity: '30 days',
    retail_price: 600,
    wholesale_price: 460,
    vtu_plan_code: 'GLO_SME_2GB_30',
    featured: false,
  },
  glo_5gb_30d: {
    id: 'glo_5gb_30d',
    network: 'Glo',
    name: '5GB — 30 Days',
    data_size: '5GB',
    validity: '30 days',
    retail_price: 1400,
    wholesale_price: 1100,
    vtu_plan_code: 'GLO_SME_5GB_30',
    featured: false,
  },

  // 9mobile Plans
  mobile9_1gb_30d: {
    id: 'mobile9_1gb_30d',
    network: '9mobile',
    name: '1GB — 30 Days',
    data_size: '1GB',
    validity: '30 days',
    retail_price: 300,
    wholesale_price: 230,
    vtu_plan_code: '9MOBILE_SME_1GB_30',
    featured: true,
  },
  mobile9_2gb_30d: {
    id: 'mobile9_2gb_30d',
    network: '9mobile',
    name: '2GB — 30 Days',
    data_size: '2GB',
    validity: '30 days',
    retail_price: 600,
    wholesale_price: 460,
    vtu_plan_code: '9MOBILE_SME_2GB_30',
    featured: false,
  },
};

export const PLANS_BY_NETWORK = {
  MTN: [
    PLANS.mtn_500mb_7d,
    PLANS.mtn_1gb_30d,
    PLANS.mtn_2gb_30d,
    PLANS.mtn_5gb_30d,
    PLANS.mtn_10gb_30d,
  ],
  Airtel: [
    PLANS.airtel_500mb_7d,
    PLANS.airtel_1gb_30d,
    PLANS.airtel_2gb_30d,
    PLANS.airtel_5gb_30d,
  ],
  Glo: [PLANS.glo_1gb_30d, PLANS.glo_2gb_30d, PLANS.glo_5gb_30d],
  '9mobile': [PLANS.mobile9_1gb_30d, PLANS.mobile9_2gb_30d],
};
